import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/providers/react-query-provider";
import { SocketProvider } from "@/components/providers/socket-provider";
import { ContextProvider } from "@/components/providers/context-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ContextProvider>
            <SocketProvider>{children}</SocketProvider>
          </ContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
